### ISSUE TITLE
Question: pybecker command not available after install what do I do wrong?

### ISSUE THREAD

**Issue by benganellison** [nicolasberthel/pybecker#4]
Hi,

After installing the pybecker using 

`python3.7 -m pip install pybecker
`

 i can not use the command using pybecker. 

```
$ pybecker
pybecker: command not found
```

But if i do
`cd ~/.local/lib/python3.7/site-packages`

the following command works. 
`python3.7 pybecker -c 1:1 -a UP`

**Comment by holgeradam** [comment]
I was able to start it from any location using `python3 -m pybecker -h` . Apparently it needs the m flag to indicate starting the module as a script.

**Comment by benganellison** [comment]
the -m flag works for me
